### ISSUE TITLE
Should caseOn be flipped?

### ISSUE THREAD

**Issue by JAForbes** [paldepind/union-type#47]
In order to use caseOn as a reducer it would be more convenient to have caseOn parameter order reversed.

I noticed in the functional frontend architecture that caseOn is flipped there as well.

I realise this is a breaking change, but I wonder if there some way to solve this, or if there was some reason the arguments were in the other order in the first place.

**Comment by paldepind** [comment]
Maybe. I'm not sure. `caseOn` should definitely work as a reducer function. But the problem is whether or not a reducer function takes it's accumulator first or last. When doing functional programming I believe `a -> b -> b`, i.e. the accumulator last, is most convenient. However that is not the typical order in JavaScript. So maybe is should be changed.

**Comment by JAForbes** [comment]
@paldepind That is interesting.  Why would accumulator last be more convenient?   I am trying to imagine the ramifications of that.

**Comment by davidchambers** [comment]
For what it's worth Haskell's [`foldl`][1] is of the following type:

```haskell
foldl :: Foldable t => (b -> a -> b) -> b -> t a -> b
```


[1]: http://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Foldable.html#v:foldl

**Comment by paldepind** [comment]
Exactly. The other argument order is much better for currying where functions take the structure to modify as the last element.

@davidchambers, in Haskell you most often use `foldr` which has the "correct" order.
